# Generated by Django 5.2.3 on 2025-08-20 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kategoriya', models.CharField(max_length=65)),
                ('Tavsif', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=150)),
                ('Mutaxassislik', models.CharField(choices=[('Milliy oshpazlik', 'Milliy oshpazlik'), ('Shirinlik', 'Shirinlik'), ('Salat', 'Salat')])),
                ('Tajriba', models.IntegerField()),
                ('Bio', models.TextField()),
                ('Email', models.EmailField(max_length=150)),
                ('telefon', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='plater',
            name='club',
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomi', models.CharField(max_length=120)),
                ('Ingredientlar', models.TextField()),
                ('Yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('Chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.chef')),
                ('Kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='Plater',
        ),
    ]
