# Generated by Django 5.2.3 on 2025-08-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_category_chef_remove_plater_club_recipe_delete_club_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Kategoriya',
            new_name='kategoriya',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Tavsif',
            new_name='tavsif',
        ),
        migrations.RenameField(
            model_name='chef',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='chef',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='chef',
            old_name='Full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='chef',
            old_name='Mutaxassislik',
            new_name='mutaxassislik',
        ),
        migrations.RenameField(
            model_name='chef',
            old_name='Tajriba',
            new_name='tajriba',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Chef',
            new_name='chef',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Ingredientlar',
            new_name='ingredientlar',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Kategoriya',
            new_name='kategoriya',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Nomi',
            new_name='nomi',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Yaratilgan',
            new_name='yaratilgan',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tavsif',
            field=models.TextField(default="tavsif yo'q"),
        ),
    ]
